"""Shared Pydantic models for inter-stage pipeline contracts."""

from __future__ import annotations

from pydantic import BaseModel, Field, model_validator


class Shot(BaseModel):
    """A single visual shot within a tutorial section."""

    id: str
    start_sec: float = Field(ge=0)
    end_sec: float = Field(ge=0)
    visual: str
    action: str
    on_screen_text: str = ""

    @model_validator(mode="after")
    def _end_after_start(self) -> Shot:
        if self.end_sec <= self.start_sec:
            msg = f"Shot {self.id}: end_sec ({self.end_sec}) must be > start_sec ({self.start_sec})"
            raise ValueError(msg)
        return self


class Section(BaseModel):
    """A logical section of the tutorial script."""

    id: str
    title: str
    target_seconds: int = Field(ge=5, le=120)
    narration: str
    key_points: list[str]
    shots: list[Shot]


class TutorialScript(BaseModel):
    """Complete tutorial script generated by the script stage."""

    topic: str
    audience: str = "data scientists"
    total_target_seconds: int = Field(le=300)
    estimated_words: int
    hook: str
    sections: list[Section]
    recap: str
    cta: str


class ResearchResult(BaseModel):
    """Output from the research stage — gathered source material for script generation."""

    topic: str
    sources: list[str] = Field(default_factory=list, description="URLs or reference titles")
    key_findings: list[str] = Field(
        default_factory=list,
        description="Bullet-point facts and insights",
    )
    code_examples: list[str] = Field(
        default_factory=list,
        description="Runnable code snippets relevant to the topic",
    )
    raw_notes: str = Field(default="", description="Unstructured research notes from the LLM")


class CritiqueScores(BaseModel):
    """Individual category scores for tutorial critique (1-10 each)."""

    accuracy: float = Field(ge=1, le=10, description="Are facts consistent with research?")
    completeness: float = Field(ge=1, le=10, description="Does it cover key findings?")
    pacing: float = Field(ge=1, le=10, description="Is narration density appropriate?")
    audience_fit: float = Field(ge=1, le=10, description="Is content right for audience?")
    teaching_effectiveness: float = Field(
        ge=1, le=10, description="Good pedagogy (hook, examples, recap)?",
    )


class CritiqueResult(BaseModel):
    """Self-critique output evaluating the generated tutorial."""

    scores: CritiqueScores
    overall_grade: float = Field(ge=1, le=10, description="Weighted overall score")
    strengths: list[str] = Field(default_factory=list)
    improvements: list[str] = Field(default_factory=list)
    summary: str = ""


class StageResult(BaseModel):
    """Output contract returned by each pipeline stage."""

    stage: str
    success: bool
    output_path: str
    metadata: dict[str, str | int | float] = {}


class TimingSegment(BaseModel):
    """A single named timing segment within a tutorial."""

    id: str
    start_ms: int
    end_ms: int
    text: str = ""


class TimingManifest(BaseModel):
    """Timing manifest shared between TTS, recording, and editing stages."""

    total_duration_ms: int
    segments: list[TimingSegment]

    def slot_duration_ms(self, index: int) -> int:
        """Duration from this segment's start to the next segment's start (or end)."""
        if index + 1 < len(self.segments):
            return self.segments[index + 1].start_ms - self.segments[index].start_ms
        return self.end_ms_for(index) - self.segments[index].start_ms

    def end_ms_for(self, index: int) -> int:
        return self.segments[index].end_ms
