"""Shared Pydantic models for inter-stage pipeline contracts."""

from __future__ import annotations

from pydantic import BaseModel, Field, model_validator


class Shot(BaseModel):
    """A single visual shot within a tutorial section."""

    id: str
    start_sec: float = Field(ge=0)
    end_sec: float = Field(ge=0)
    visual: str
    action: str
    on_screen_text: str = ""

    @model_validator(mode="after")
    def _end_after_start(self) -> Shot:
        if self.end_sec <= self.start_sec:
            msg = f"Shot {self.id}: end_sec ({self.end_sec}) must be > start_sec ({self.start_sec})"
            raise ValueError(msg)
        return self


class Section(BaseModel):
    """A logical section of the tutorial script."""

    id: str
    title: str
    target_seconds: int = Field(ge=5, le=120)
    narration: str
    key_points: list[str]
    shots: list[Shot]


class TutorialScript(BaseModel):
    """Complete tutorial script generated by the script stage."""

    topic: str
    audience: str = "data scientists"
    total_target_seconds: int = Field(le=300)
    estimated_words: int
    hook: str
    sections: list[Section]
    recap: str
    cta: str


class ResearchResult(BaseModel):
    """Output from the research stage — gathered source material for script generation."""

    topic: str
    sources: list[str] = Field(default_factory=list, description="URLs or reference titles")
    key_findings: list[str] = Field(
        default_factory=list,
        description="Bullet-point facts and insights",
    )
    code_examples: list[str] = Field(
        default_factory=list,
        description="Runnable code snippets relevant to the topic",
    )
    raw_notes: str = Field(default="", description="Unstructured research notes from the LLM")


class CritiqueResult(BaseModel):
    """Self-critique output evaluating the generated tutorial."""

    scores: dict[str, float] = Field(
        default_factory=dict,
        description=(
            "Category scores (1-10): accuracy, completeness, "
            "pacing, audience_fit, teaching_effectiveness"
        ),
    )
    overall_grade: float = Field(ge=1, le=10, description="Weighted overall score")
    strengths: list[str] = Field(default_factory=list)
    improvements: list[str] = Field(default_factory=list)
    summary: str = ""


class StageResult(BaseModel):
    """Output contract returned by each pipeline stage."""

    stage: str
    success: bool
    output_path: str
    metadata: dict[str, str | int | float] = {}
